2017-02-17 16:56:18,523 (INFO) update
2017-02-17 16:56:19,002 (INFO) Convert data ...
2017-02-17 16:56:32,541 (INFO) update
2017-02-17 16:56:32,962 (INFO) Update device ...
2017-02-17 16:56:33,007 (ERROR) Test/test.py:42 - [Errno 2] No such file or directory: 'sdfe'
Traceback (most recent call last):
  File "/Users/daiyanze/Desktop/alpha/Library/Utils/Logger.py", line 101, in wrapper
    return argument(*args, **kwargs)
  File "Test/test.py", line 42, in test
    raise e
  File "Test/test.py", line 40, in test
    open('sdfe')
FileNotFoundError: [Errno 2] No such file or directory: 'sdfe'
